version: '3'
services:
  mysqldb:
    image: mysql:latest
    ports:
     - "3306:3306"
    environment:
     - MYSQL_ROOT_PASSWORD=srivatsan
     - MYSQL_DATABASE=test
    volumes:
      - mysqldb:/var/lib/mysql
  myspringapp:
    image: myapplication
    build:
      context: ./
    ports:
      - "8070:8080"
    depends_on:
      - mysqldb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/test
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=srivatsan
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
volumes:
  mysqldb:
    driver: local      
      