server:
  port: 5050
spring:
  application:
    name: book-service-client  
  

eureka:
  instance:    prefer-ip-address: true  client:    fetch-registry: true
    register-with-eureka: true
    service-url:      defaultZone: http://localhost:8761/eureka  